name: locatr
description: A companion app to the locatr tracker

version: 0.0.1+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  google_maps_flutter: ^0.5.21+12
  location: ^2.3.5
  google_sign_in: ^4.0.11
  firebase_auth: ^0.14.0+8
  # simple_animations: ^
  # firebase_storage: ^3.0.8
  # firebase_database: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.4"

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  image_path: "../assets/logos/logo_app.png"

flutter:
  uses-material-design: true
  assets:
    - ../assets/logos/logo_transparent.png
    - ../assets/logos/google.png

  fonts:
    - family: Raleway
      fonts:
        - asset: ../assets/fonts/raleway/Raleway-Regular.ttf
        - asset: ../assets/fonts/raleway/Raleway-Italic.ttf
          style: italic
        - asset: ../assets/fonts/raleway/Raleway-Light.ttf
          weight: 300
        - asset: ../assets/fonts/raleway/Raleway-SemiBold.ttf
          weight: 600
        - asset: ../assets/fonts/raleway/Raleway-Bold.ttf
          weight: 700
